### ISSUE TITLE
500 Error when trying to get ♀

### ISSUE THREAD

**Issue by rbaehr** [benborgers/emojicdn#34]
There's a 500 error on the API when trying to retrieve "♀"

https://emojicdn.elk.sh/%E2%99%80

![image](https://user-images.githubusercontent.com/8263162/186721083-fc5daf42-e954-4232-93c4-44976e507755.png)

**Comment by benborgers** [comment]
Thanks for catching this! It was due to new elements that Emojipedia added to the page. I’ve fixed the bug in c0a9238b1c4296404ad40e311900141fa1513539. 

Note that Apple doesn’t have a version of that emoji (and the API defaults to Apple-style emojis), so you’ll have to do something like: https://emojicdn.elk.sh/♀?style=google
